### ISSUE TITLE
Trouble when trying to catch the ip field

### ISSUE THREAD

**Issue by SiskonEmilia** [Dev-iL/pcap2matlab#3]
It seems that your function try to convert every IP address into a double type, and all those efforts results in NANs.

**Comment by Dev-iL** [comment]
Hi there!
The majority of the code wasn't written by me (my effort focused on optimization and cleanup).

Would you tell me if the version on [develop](https://github.com/Dev-iL/pcap2matlab/tree/develop) fixes your problem?

**Comment by SiskonEmilia** [comment]
It seems that the latest version under development does not have this bug. Thanks :D

**Comment by RoyiAvital** [comment]
@Dev-iL , What a great name (And country!) :-).
